# Линейная Алгебра

# Матрицы и матричные операции. Часть 1

In [26]:
import numpy as np
from numpy.linalg import norm

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

`Решение:`

По свойству произведения двух матриц, результирующая матрица будет иметь длину `m` (длина строки 1-й матрицы) на `k` (длина столбца 2-й матрицы), при условии равенства длин двух других параметров. Таким образом:

а) Матрица не определена (кол-во столбцов A не совпадает с кол-вом строк B)

б) Результирующая матрица: 5 $\times$ 3

в) Результирующая матрица: 8 $\times$ 8

г) Результирующая матрица: 4 $\times$ 4

In [49]:
A11, B11 = np.eye(4,2), np.eye(4,2)
A12, B12 = np.eye(2,5), np.eye(5,3)
A13, B13 = np.eye(8,3), np.eye(3,8)
A14, B14 = np.eye(4,4), np.eye(4,4)

In [104]:
# > np.dot(A11, B11) 
# < ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [51]:
print(f'Размер 2-й матрицы: {np.dot(A12, B12).shape}')
print(f'Размер 3-й матрицы: {np.dot(A13, B13).shape}')
print(f'Размер 4-й матрицы: {np.dot(A14, B14).shape}')

Размер 2-й матрицы: (2, 3)
Размер 3-й матрицы: (8, 8)
Размер 4-й матрицы: (4, 4)


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

`Решение:`

$$A + B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} +
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1 + 4 & -2 + (-1)\\ 
3 + 0 & 0 + 5
\end{pmatrix} = 
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix},
$$

$$A \times B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1\cdot 4 + (-2)\cdot 0 & 1\cdot(-1) + (-2)\cdot 5\\ 
3\cdot 4 + 0\cdot 0 & 3\cdot(-1) + 0\cdot 5
\end{pmatrix} = 
\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.
$$

$$B \times A = 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \cdot
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = 
\begin{pmatrix}
4\cdot 1 + (-1)\cdot 3 & 4\cdot(-2) + (-1)\cdot 0\\ 
0\cdot 1 + 5\cdot 3 & 0\cdot(-2) + 5\cdot 0
\end{pmatrix} = 
\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}.
$$

In [206]:
A21 = np.array([
    [1,-2],
    [3,0]
])

B21 = np.array([
    [4,-1],
    [0,5]
])

print(A21 + B21)
print()
print(np.dot(A21,B21))
print()
print(np.dot(B21,A21))

[[ 5 -3]
 [ 3  5]]

[[  4 -11]
 [ 12  -3]]

[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

`Решение:`

In [62]:
A31 = np.array([
    [1,7],
    [3,-6]
])

B31 = np.array([
    [0,5],
    [2,-1]
])

C31 = np.array([
    [2,-4],
    [1,1]
])

3 * A31 - 2 * B31 + 4 * C31

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

`Решение:`

$AA^T = 
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}
\cdot
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3 
\end{pmatrix}
=
\begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3\\ 
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) & 5 \cdot 2 + (-2) \cdot 3\\ 
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3
\end{pmatrix}
=
\begin{pmatrix}
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}$

$A^TA = 
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3 
\end{pmatrix}
\cdot
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}
=
\begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3\\ 
1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + (-2) \cdot (-2) + 3 \cdot 3
\end{pmatrix}
=
\begin{pmatrix}
45 & 0 \\
0 & 14
\end{pmatrix}$

In [27]:
A41 = np.array([
    [4,1],
    [5,-2],
    [2,3]
])
print(np.dot(A41, A41.T))
print()
print(np.dot(A41.T, A41))

[[17 18 11]
 [18 29  4]
 [11  4 13]]

[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [94]:
def mat_mul(A, B): # На входе 2 матрицы (list)
    res = [[0 for x in range(len(A))] for y in range(len(B[0]))] # Генерация результирующей матрицы
    assert len(A[0]) == len(B)
    for i in range (len(A)):
        for j in range(len(B[0])):
            for k in range (len(A[0])): # Итерация по каждому элементу матрицы с учетом общей размерности.
                res[i][j] += A[i][k] * B[k][j]
    return res

In [95]:
A = [[1,2,3,4],[3,4,2,1],[5,6,2,1]]
B = [[1,2,1],[4,5,1], [5,5,1], [2,7,1]]
# A, B = np.eye(10,5), np.eye(5,10)
print(mat_mul(A,B))

[[32, 55, 10], [31, 43, 10], [41, 57, 14]]


In [96]:
print(np.dot(A,B))

[[32 55 10]
 [31 43 10]
 [41 57 14]]


# Матрицы и матричные операции. Часть 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


`Решение:`

__a)__

$$det 
\begin{vmatrix}
\sin x & -\cos x\\ 
\cos x & \sin x
\end{vmatrix}
=
\sin x \cdot \sin x + \cos x \cdot \cos x  = 1$$

In [98]:
x = 12345

A_11 = np.array([
    [np.sin(x), -np.cos(x)],
    [np.cos(x), np.sin(x)]
])

round(np.linalg.det(A_11))

1.0

__б)__

$$det
\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}
=
4\cdot\begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix}-
2\cdot\begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
0 & 5\\ 
0 & 0
\end{vmatrix}
=
4\cdot(5\cdot9) - 2\cdot0 + 3\cdot 0 = 180
$$

In [84]:
A_12 = np.array([
    [4,2,3],
    [0,5,1],
    [0,0,9]
])
np.linalg.det(A_12)

180.0

__в)__

$$det
\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}
=
((1\cdot 5 \cdot 9) + (2 \cdot 6 \cdot 7) + (4 \cdot 8 \cdot 3) - ((3 \cdot 5 \cdot 7) + (6 \cdot 8 \cdot 1) + (2 \cdot 4 \cdot 9))
= (45 + 84 + 96) - (105 + 48 + 72) = 0 
$$

In [103]:
A_13 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
round(np.linalg.det(A_13))

-0.0

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

`Решение:`

- При возведении матрицы в степень, определитель получит такую же степень
- Определители транспонированной матрицы равен определителю исходной
- При умножении матрицы на число, определитель матрицы будет умножен на то же число в степени, равной количеству строк/столбцов.

In [191]:
A_21 = np.array([
    [4,2,2],
    [1,4,1],
    [1,2,1]
])
round(np.linalg.det(A_21))

4.0

In [192]:
print(round(np.linalg.det(np.dot(A_21,A_21))))
print(round(np.linalg.det(A_21.T)))
print(round(np.linalg.det(2 * A_21)))

16.0
4.0
32.0


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



`Решение:`

Матрица называется сингулярной, или __вырожденной__, если ее __определитель равен нулю__

$$det
\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix}
=
((-2\cdot -14 \cdot 13) + (7 \cdot 6 \cdot -3) + (4 \cdot 7 \cdot -3) - ((-3 \cdot -14 \cdot -3) + (4 \cdot 7 \cdot 13) + (7 \cdot 6 \cdot -2))
= (154) - (154) = 0 
$$

In [194]:
A_31 = np.array([
    [-2,7,-3],
    [4,-14,6],
    [-3,7,13]
])
round(np.linalg.det(A_31))

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

`Решение:`

__a)__


Третья строка является вырожденной (сумма первой и второй). 

Видно, что как минимум 1 минор 2-го порядка имеет ненулевой определитель, соответственно ранг матрицы равен 2

__б)__

Первый столбец имеет линейную зависимость от 2-го (умножаем на -1.5 и складываем).

Нетрудно заметить, что определитель минора 3-го порядка
$\begin{vmatrix}
0 & 2 & 2\\ 
0 & 4 & 3\\ 
3 & 5 & 6
\end{vmatrix}
$ отличен от нуля, и равен - 6, соответственно, ранг матрицы равен 3

In [195]:
A_41 = np.array([
    [1,2,3],
    [1,1,1],
    [2,3,4]
])

A_42 = np.array([
    [0,0,2,1],
    [0,0,2,2],
    [0,0,4,3],
    [2,3,5,6]
])

In [204]:
np.linalg.matrix_rank(A_41)

2

In [205]:
np.linalg.matrix_rank(A_42)

3

__* Построить ортогональную матрицу, сравнить результат транспонирования и нахождения обратной матрицы__

In [244]:
# Матрица подстановки
A0 = np.array([
    [0,0,0,1],
    [0,0,1,0],
    [1,0,0,0],
    [0,1,0,0]
])
print('A matrix:\n')
print(A0,'\n')
print('A.inv:\n')
print(np.linalg.inv(A0),'\n')
print('A * A.T:\n')
print(np.dot(A0, A0.T),'\n')
print('A * A.inv:\n')
print(np.dot(np.linalg.inv(A0), A0))

A matrix:

[[0 0 0 1]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]] 

A.inv:

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]] 

A * A.T:

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 

A * A.inv:

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [261]:
# Матрица поворота
A01 = np.array([
    [0.96,-0.28],
    [0.28,0.96]
])
print('A matrix:\n')
print(A01,'\n')
print('A.inv:\n')
print(np.linalg.inv(A01),'\n')
print('A * A.T:\n')
print(np.dot(A01, A01.T).round(),'\n')
print('A * A.inv:\n')
print(np.dot(np.linalg.inv(A01), A01).round(),'\n')

A matrix:

[[ 0.96 -0.28]
 [ 0.28  0.96]] 

A.inv:

[[ 0.96  0.28]
 [-0.28  0.96]] 

A * A.T:

[[1. 0.]
 [0. 1.]] 

A * A.inv:

[[1. 0.]
 [0. 1.]] 

