# Линейная Алгебра

# Системы линейных уравнений. Часть 1

In [1]:
import numpy as np
from scipy import linalg as lg

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

`Решение:`

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Прибавим ко 2-й и 3-й строке 1-ю, умноженную на -2 и -1:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

$$\begin{cases}
x_{1}+x_{2}-x_{3} - 2x_{4}=0 \\
~~~ -x_{2}+x_{3} + x_{4}=-2 \\
~~~~~~~~~~ -2x_{3} + 3x_{4} = 4
\end{cases}$$

Система имеет бесконечное множество решений, $x_4$ - свободный член, _общее решение_ имеет вид:

$$\begin{cases}
x_{1} = -3x_4 -2 \\
x_{2} = 6.5x_4 \\
x_3 = 1.5x_4 -2
\end{cases}$$

In [7]:
A1  = np.array([[1,1,-1,-2],[2,1,-1,1],[1,1,-3,1]])
B1  = np.array([[1,1,-1,-2, 0],[2,1,-1,1, -2],[1,1,-3,1, 4]])
print(np.linalg.matrix_rank(A1))
print(np.linalg.matrix_rank(B1))

3
3


__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

`Решение:`

__в)__ система недоопределена, имеет бесконечное число решений

In [17]:
A21  = np.array([[3,-1,1],[2,-5,-3],[1,1,-1]])
B21 = np.array([[3,-1,1,4],[2,-5,-3,-17],[1,1,-1,0]])

A22  = np.array([[2,-4,6],[1,-2,3],[3,-6,9]])
B22 = np.array([[2,-4,6,1],[1,-2,3,-2],[3,-6,9,5]])

A23  = np.array([[1,2,5],[3,1,-8]])
B23 = np.array([[1,2,5,4],[3,1,-8,-2]])

def get_comp(mat_A, mat_B):
    a = np.linalg.matrix_rank(mat_A)
    b = np.linalg.matrix_rank(mat_B)
    if a == b and b == len(mat_A[0]):
        return "Система имеет единственное решение"
    if a == b and b < len(mat_A[0]):
        return "Система имеет бесконечное число решений"
    if a < b:
        return "Система несовместна"
    
print(f'а) {get_comp(A21,B21)}')
print(f'б) {get_comp(A22,B22)}')
print(f'в) {get_comp(A23,B23)}')

а) Система имеет единственное решение
б) Система несовместна
в) Система имеет бесконечное число решений


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

`Решение:`

Из заданной системы видно, что $rank$ $A = rank$ $\tilde{A} = 4$, количество неизвестных $n=4$, таким образом выполняется условие теоремы Кронекера — Капелли для определенной матрицы с единственным решением.

In [22]:
A31  = np.array([[1,3,-2,4],[0,5,0,1],[0,0,3,0],[0,0,0,2]])
B31 = np.array([[1,3,-2,4,3],[0,5,0,1,2],[0,0,3,0,4],[0,0,0,2,1]])
print(f' {get_comp(A31, B31)}')

 Система имеет единственное решение


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

`Решение:`

Достаточным условием несовместности системы является: $rankA<rank \tilde A$, приведем систему к диагональному виду:

$$\tilde{A}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix} 
=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}
=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a-2b
\end{matrix}
\end{pmatrix}
$$

$$\tilde{A}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix} 
=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a
\end{matrix}
\end{pmatrix}
=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a-2b
\end{matrix}
\end{pmatrix}
$$

Таким образом, система будет несовместна при соблюдении соотношения __`c-3a-2b`__, или __`c-7a-2b`__

# Системы линейных уравнений. Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

`Решение:`

__а)__

Найдем определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
1 & -2\\ 
3 & -4 
\end{vmatrix}
=-4 + 6 =2\neq 0,$$

Найдем определители $detA_{1}$, $detA_{2}$

$$detA_1=\begin{vmatrix}
1 & -2\\ 
7 & -4 
\end{vmatrix}
=-4+14 = 10$$

$$detA_2=\begin{vmatrix}
1 & 1\\ 
3 & 7 
\end{vmatrix}
=7-3 = 4$$

Найдем решение по формулам Крамера:

$$x_1 = \frac{10}{2} = 5 $$

$$x_2 = \frac{4}{2} = 2$$

__б)__

Найдем определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+
5\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=2(1 + 12)+7+5(4-2)=43\neq 0,$$

Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

$$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}=
10\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}+
5\begin{vmatrix}
-2 & 1 \\ 
1 & 4
\end{vmatrix}=10(1 + 12)+1+5(-8-1)=86$$

$$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}=
2\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}-
10\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+
5\begin{vmatrix}
1 & -2 \\ 
2 & 1
\end{vmatrix}=2(-2+3)-10(1+6)+5(1+4)=2-70+25=-43$$

$$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -2\\ 
4 & 1
\end{vmatrix}+
\begin{vmatrix}
1 & 2\\ 
-2 & 1 
\end{vmatrix}+
10\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=2(1+8)+5+10(4-2)=18+5+20=43$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$

$$x_{2} = \frac{detA_{2}}{detA} = -\frac{43}{43}=-1,$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1.$$

__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
   

`Решение:`

__а)__

$$L=\begin{pmatrix}
1 & 0 & 0\\ 
m_{21} & 1 & 0\\ 
m_{31} & m_{32} & 1
\end{pmatrix}
=
\begin{pmatrix}
1 & 0 & 0\\ 
2 & 1 & 0\\ 
3 & 10 & 1
\end{pmatrix}
$$

Преобразование матрицы коэффициентов $A$:

$$\begin{pmatrix}
1 & 2 & 4\\ 
0 & 5 & 4\\ 
0 & 20 & 18
\end{pmatrix}
=
\begin{pmatrix}
1 & 2 & 4\\ 
0 & 5 & 4\\ 
0 & 0 & -22
\end{pmatrix}
$$

In [84]:
A_21 = np.array([
    [1,2,4],
    [2,9,12],
    [3,26,30]
])

P, L, U = lg.lu(A_21)
print(f'P:\n {P}\nL:\n {L}\nU:\n {U}\n')

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]
U:
 [[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]



__б)__

$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
m_{21} & 1 & 0 & 0\\ 
m_{31} & m_{32} & 1 & 0\\ 
m_{41} & m_{42} & m_{43} & 1\\ 
\end{pmatrix}
=
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\ 
4 & 6 & 7 & 1\\ 
\end{pmatrix}
$$

Преобразование матрицы коэффициентов $A$:
$$
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\ 
4 & 22 & 53 & 33\\ 
\end{pmatrix}
=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\ 
0 & 18 & 45 & 17\\ 
\end{pmatrix}
=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\ 
0 & 0 & 21 & 11\\ 
\end{pmatrix}
=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\ 
0 & 0 & 0 & 4\\ 
\end{pmatrix}
$$

In [85]:
A_22 = np.array([
    [1,1,2,4],
    [2,5,8,9],
    [3,18,29,18],
    [4,22,53,33]
])
P, L, U = lg.lu(A_22)
print(f'P:\n {P}\nL:\n {L}\nU:\n {U}\n')

P:
 [[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
L:
 [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75       -0.25        1.          0.        ]
 [ 0.25        0.75       -0.17073171  1.        ]]
U:
 [[  4.          22.          53.          33.        ]
 [  0.          -6.         -18.5         -7.5       ]
 [  0.           0.         -15.375       -8.625     ]
 [  0.           0.           0.          -0.09756098]]



__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

`Решение:`

Матрица коэффициентов $A$ будет иметь вид

$$
\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}
=
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 3.5 & -9.5
\end{pmatrix}
=
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & -20
\end{pmatrix}
$$

Матрицы $LU$-разложения

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & 3.5 & 1
\end{pmatrix}.$$

$$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & -20
\end{pmatrix},$$

Решим теперь систему 

$$Ly=b:$$

$$\begin{cases}
y_{1}=1, \\
5.5y_{1}+y_{2}=-6, \\
4.5y_{1}+3.5y_{2}+y_{3}=-5.
\end{cases}$$

$y_{1}=1,$

$y_{2}=-11.5,$

$y_{3}=-5-4.5-3.5\cdot(-11.5)=30.75.$

И затем систему

$$Ux=y:$$

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
1.5x_{2}-11.5x_{3}=-11.5, \\
-20x_{3}=30.75.
\end{cases}$$

$x_{3}=-1.5375,$

$x_{2}=-\frac{11.5+11.5\cdot(-1.5375)}{1.5}=-19.454,$

$x_{1}=\frac{1-(-19.454)-3\cdot(-1.5375)}{2}=12.53325.$

Произведем проверку, подставив полученные значения переменных в исходную систему:

In [1]:
x3 = -1.5375
x2 = -19.454
x1 = 12.53325
print(f'{2*x1+1*x2+3*x3}')
print(f'{11*x1+7*x2+5*x3}')
print(f'{9*x1+8*x2+4*x3} - не сходится') 

1.0
-5.9997499999999775
-48.98275 - не сходится


In [76]:
# LU-разложение с помощью scipy

A_3 = np.array([[2,1,3],[11,7,5],[9,8,4]])
b_3 = np.array([1, -6, -5])

P, L, U = lg.lu(A_3)
print(f'P:\n {P}\nL:\n {L}\nU:\n {U}\n')

lu, piv = lg.lu_factor(A_3)
x = lg.lu_solve((lu, piv), b_3)
print(f'LU scipy-solution: {x}')

P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L:
 [[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]
U:
 [[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]

LU scipy-solution: [-1.00000000e+00  2.44249065e-16  1.00000000e+00]


In [80]:
"""reference: 

https://slemeshevsky.github.io/python-num-pde/term1/build/html/_sles/gauss.html#sles-lu"""

def gauss(x): 
    x = np.array(x,float)
    return x[1:]/x[0]

def gauss_app(C, t):
    C = np.array(C, float)
    t = np.array([[t[i]] for i in range(len(t))], float)
    C[1:,:] = C[1:,:] - t*C[0,:]
    return C
def lu(A):
    LU = np.array(A, float)
    for k  in range(LU.shape[0]-1):
        t = gauss(LU[k:, k])
        LU[k+1:,k] = t
        LU[k:, k+1:] = gauss_app(LU[k:, k+1:], t)
    return LU

def solve_lu(A, b):
    LU = lu(A)
    b = np.array(b,float)
    for i in range(1,len(b)):
        b[i] = b[i] - np.dot(LU[i,:i],b[:i])
    for i in range(len(b)-1, -1, -1):
        b[i] = (b[i] - np.dot(LU[i,i+1:],b[i+1:]))/LU[i,i]
    return b

In [82]:
print(f'LU func-solution: {solve_lu(A_3, b_3)}')

LU func-solution: [-1.  0.  1.]


In [4]:
x1 = -1
x2 = 0
x3 = 1
print(f'{2*x1+1*x2+3*x3}')
print(f'{11*x1+7*x2+5*x3}')
print(f'{9*x1+8*x2+4*x3}') 

1
-6
-5


__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

`Решение:`

In [15]:
A_4 = np.array([
    [81,-45,45],
    [-45,50,-15],
    [45,-15,38]
])
b_4 = np.array([531,-460,193])

In [16]:
lu, piv = lg.lu_factor(A_4)
x = lg.lu_solve((lu, piv), b_4)
print(f'LU scipy-solution: {x}')

LU scipy-solution: [ 6. -5. -4.]


In [28]:
def ld(A):
    """
    Для симметричной матрицы A вычисляет нижнюю
    треугольную матрицу L и диагональную матрицу 
    D, такие что A = LDL^T. Элементы a_{ij} замещаются 
    на l_{ij}, если i > j, и на d_i, если i = j
    """
    n = len(A)
    LD = np.array(A, float)
    L = np.array(A,float)
    for j in range(n):
        v = np.zeros(j+1)
        v[:j] = LD[j,:j]*LD[range(j),range(j)]
        v[j] = LD[j,j] - np.dot(LD[j,:j],v[:j])
        LD[j,j] = v[j]
        LD[j+1:,j] = (LD[j+1:,j] - np.dot(LD[j+1:,:j],v[:j]))/v[j]

    return LD

def ld_solve(A, b):
    """
    Решает систему Ax = b c использованием LDL^T-разложения
    """
    LD = ld(A)
    b = np.array(b,float)
    for i in range(1, len(b)):
        b[i] = b[i] - np.dot(LD[i,:i],b[:i])
    b[:] = b[:]/LD[range(len(b)),range(len(b))]
    for i in range(len(b)-1, -1, -1):
        b[i] = (b[i] - np.dot(LD[i+1:,i],b[i+1:]))
    return b

In [30]:
ld_solve(A_4,b_4)

array([ 6., -5., -4.])